# Barter analysis: interesting metrics

# Ideas

- Timeline of active partners/ creators over time (bar chart race)

# Init

In [2]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy import text

import numpy as np
import pandas as pd

from src.utils import interactive_dataframe_selector

In [3]:
# Load environment variables from .env file
load_dotenv("../private_data/.env")

host = os.getenv("HOST")
db = os.getenv("DB")
port = os.getenv("PORT")
role = os.getenv("ROLE")
pw = os.getenv("PASSWORD")
engine = create_engine(f"postgresql+psycopg2://{role}:{pw}@{host}:{port}/{db}")

# Partners

In [3]:
query = 'SELECT * FROM public.partners;'

with engine.connect() as connection:
    # 2. We don't use parse_dates=True here to avoid the crash
    df_partners = pd.read_sql(text(query), connection)

In [14]:
df_partners

,legacy_id,user_id,name,customer_id,status,created_at,updated_at,deleted_at,tags,id,company_name,company_size,website,worked_with_creators,references,reference_reason
0,2418,50843,Derrick Homenick,,PhoneNumberVerification,2025-09-10 10:22:57.281581+00:00,2025-09-10 10:22:57.462205+00:00,None,None,01993326-6101-0065-d61a-bd22529ce9d4,,None,,None,None,
1,2423,50849,Maudie Robel,,PhoneNumberVerification,2025-09-10 10:53:28.037275+00:00,2025-09-10 10:53:28.195740+00:00,None,None,01993342-5065-0065-07e9-732563162928,,None,,None,None,
2,2466,51011,Mr. Randy Towne,,Active,2025-09-11 13:37:35.616499+00:00,2026-01-12 07:33:52.670102+00:00,None,[partner.companies_migration_phase1],019938fe-ef2f-0065-e1c4-ab707831a79c,Pasje.pro,xs,https://pasje.pro,False,{email},
3,2473,51059,Yolanda Simonis,,Active,2025-09-12 07:53:59.137731+00:00,2026-01-12 07:33:56.151421+00:00,None,[partner.companies_migration_phase1],01993cea-b637-0065-7b0e-11a4e54df9bb,Casa Vivida,xs,https://casa-vivida.com/,False,{google},
4,2515,51315,Mara Rempel,,Active,2025-09-16 11:56:12.117224+00:00,2026-01-12 07:34:09.754172+00:00,None,[partner.companies_migration_phase1],01995261-e7d5-0065-a052-db1b9956bdcd,jomaroto Cosmetics GmbH,xs,h-rootine.de,False,"{google,social_media,newsletter,other}",Instagram
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3933,0,66776,Testing,,CompanyInformation,2026-02-10 16:22:22.864561+00:00,2026-02-10 16:22:28.397058+00:00,None,None,019c485c-6d90-0065-5aaf-dcdf141ae162,,None,,None,None,
3934,0,66771,Test Account,,Active,2026-02-04 14:45:59.787184+00:00,2026-02-04 14:46:14.780617+00:00,None,None,019c291e-076b-0065-d02d-f89615aff7ea,Trolhas,xs,Trolhas.com,True,{recommendation},
3935,0,66778,nice,,PhoneNumberVerification,2026-02-10 16:32:54.461092+00:00,2026-02-10 16:32:54.563914+00:00,None,None,019c4866-10bd-0065-11b2-609ee1a5821b,,None,,None,None,
3936,0,66779,testingdev,,SubscriptionPlan,2026-02-10 16:33:33.759390+00:00,2026-02-10 16:33:51.198583+00:00,None,None,019c4866-aa3f-0065-0875-7af641c88bca,312321321,xs,3123213213,True,"{webinar,online_ad}",
3937,0,66780,testingtesting,,CompanyInformation,2026-02-10 16:34:47.459552+00:00,2026-02-10 16:35:00.797871+00:00,None,None,019c4867-ca23-0065-6357-080edf307158,,None,,None,None,

In [18]:
df_partners.isna().sum()

legacy_id                  0
user_id                    0
name                       0
customer_id                0
status                     0
created_at                 0
updated_at                 0
deleted_at              3938
tags                    1465
id                         0
company_name            2172
company_size            2948
website                 2172
worked_with_creators    2948
references              2949
reference_reason        2172
dtype: int64

In [21]:
df_partners

,legacy_id,user_id,name,customer_id,status,created_at,updated_at,deleted_at,tags,id,company_name,company_size,website,worked_with_creators,references,reference_reason
0,2418,50843,Derrick Homenick,,PhoneNumberVerification,2025-09-10 10:22:57.281581+00:00,2025-09-10 10:22:57.462205+00:00,None,None,01993326-6101-0065-d61a-bd22529ce9d4,,None,,None,None,
1,2423,50849,Maudie Robel,,PhoneNumberVerification,2025-09-10 10:53:28.037275+00:00,2025-09-10 10:53:28.195740+00:00,None,None,01993342-5065-0065-07e9-732563162928,,None,,None,None,
2,2466,51011,Mr. Randy Towne,,Active,2025-09-11 13:37:35.616499+00:00,2026-01-12 07:33:52.670102+00:00,None,[partner.companies_migration_phase1],019938fe-ef2f-0065-e1c4-ab707831a79c,Pasje.pro,xs,https://pasje.pro,False,{email},
3,2473,51059,Yolanda Simonis,,Active,2025-09-12 07:53:59.137731+00:00,2026-01-12 07:33:56.151421+00:00,None,[partner.companies_migration_phase1],01993cea-b637-0065-7b0e-11a4e54df9bb,Casa Vivida,xs,https://casa-vivida.com/,False,{google},
4,2515,51315,Mara Rempel,,Active,2025-09-16 11:56:12.117224+00:00,2026-01-12 07:34:09.754172+00:00,None,[partner.companies_migration_phase1],01995261-e7d5-0065-a052-db1b9956bdcd,jomaroto Cosmetics GmbH,xs,h-rootine.de,False,"{google,social_media,newsletter,other}",Instagram
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3933,0,66776,Testing,,CompanyInformation,2026-02-10 16:22:22.864561+00:00,2026-02-10 16:22:28.397058+00:00,None,None,019c485c-6d90-0065-5aaf-dcdf141ae162,,None,,None,None,
3934,0,66771,Test Account,,Active,2026-02-04 14:45:59.787184+00:00,2026-02-04 14:46:14.780617+00:00,None,None,019c291e-076b-0065-d02d-f89615aff7ea,Trolhas,xs,Trolhas.com,True,{recommendation},
3935,0,66778,nice,,PhoneNumberVerification,2026-02-10 16:32:54.461092+00:00,2026-02-10 16:32:54.563914+00:00,None,None,019c4866-10bd-0065-11b2-609ee1a5821b,,None,,None,None,
3936,0,66779,testingdev,,SubscriptionPlan,2026-02-10 16:33:33.759390+00:00,2026-02-10 16:33:51.198583+00:00,None,None,019c4866-aa3f-0065-0875-7af641c88bca,312321321,xs,3123213213,True,"{webinar,online_ad}",
3937,0,66780,testingtesting,,CompanyInformation,2026-02-10 16:34:47.459552+00:00,2026-02-10 16:35:00.797871+00:00,None,None,019c4867-ca23-0065-6357-080edf307158,,None,,None,None,

In [20]:
df_partners.company_size.value_counts().sum()

np.int64(990)

In [13]:
df_partners.isna().sum()

legacy_id                  0
user_id                    0
name                       0
customer_id                0
status                     0
created_at                 0
updated_at                 0
deleted_at              3938
tags                    1465
id                         0
company_name            2172
company_size            2948
website                 2172
worked_with_creators    2948
references              2949
reference_reason        2172
dtype: int64

In [19]:
df_partners.references.value_counts() / df_partners.references.value_counts().sum()

references
{email}                                  0.277048
{google}                                 0.202224
{other}                                  0.150657
{recommendation}                         0.114257
{social_media}                           0.093023
                                           ...
{social_media,creator}                   0.001011
{webinar,creator}                        0.001011
{google,online_ad,email,social_media}    0.001011
{influencer,newsletter,webinar}          0.001011
{webinar,online_ad}                      0.001011
Name: count, Length: 62, dtype: float64

# Creators

In [10]:
query = """
SELECT 
    id, 
    user_id,
    name, 
    rating,
    description,
    status,
    created_at,
    CAST(updated_at AS TEXT) as updated_at,
    CAST(birthday AS TEXT) as birthday,
    gender,
    reviews_count
FROM public.influencers;
"""

with engine.connect() as connection:
    # 2. We don't use parse_dates=True here to avoid the crash
    df_creators = pd.read_sql(text(query), connection)

query = """
SELECT 
    created_at,
    updated_at,
    influencer_id,
    name,
    country,
    latitude,
    longitude
FROM public.influencer_locations;
"""


with engine.connect() as connection:
    # 2. We don't use parse_dates=True here to avoid the crash
    df_creatorsloc = pd.read_sql(text(query), connection)

In [11]:
# Strip the timezone from both (just to be safe)
df_creators['created_at'] = pd.to_datetime(df_creators['created_at']).dt.tz_localize(None)
df_creatorsloc['created_at'] = pd.to_datetime(df_creatorsloc['created_at']).dt.tz_localize(None)

# Now the comparison will work perfectly
mask = df_creators['created_at'] < df_creatorsloc['created_at'].min()

In [22]:
df_creatorsloc

,created_at,updated_at,influencer_id,name,country,latitude,longitude
0,2024-10-25 09:45:27.207163,2024-10-25 09:45:27.207163,16189,Almelo,Netherlands,52.367027,6.668492
1,2024-08-29 10:29:07.467566,2024-08-29 10:29:07.467566,11181,Amsterdam,Netherlands,52.367573,4.904139
2,2024-08-29 10:49:44.860592,2024-08-29 10:49:44.860592,11182,Lelystad,Netherlands,52.518537,5.471422
3,2024-08-29 10:52:50.411597,2024-08-29 10:52:50.411597,11183,Tilburg,Netherlands,51.560596,5.091914
4,2024-08-29 10:57:20.398272,2024-08-29 10:57:20.398272,11184,Amsterdam,Netherlands,52.367573,4.904139
...,...,...,...,...,...,...,...
19700,2026-01-29 23:26:56.191576,2026-01-29 23:26:56.191576,42833,Osnabrück,Germany,52.279911,8.047179
19701,2026-01-30 00:49:27.045645,2026-01-30 00:49:27.045645,42836,Sulz,Germany,48.365745,8.653955
19702,2026-01-30 02:08:44.588370,2026-01-30 02:08:44.588370,42839,Braunschweig,Germany,52.267791,10.524566
19703,2026-02-03 12:15:02.365827,2026-02-03 12:15:02.365827,2657,Nethy Bridge,United Kingdom,57.263644,-3.654089
19704,2026-02-04 14:56:18.342101,2026-02-04 14:56:18.342101,42852,Amsterdam,Netherlands,52.367573,4.904139

In [21]:
df_creators

,id,user_id,name,rating,description,status,created_at,updated_at,birthday,gender,reviews_count
0,1,2,Lennie Hermiston,5.0,,Active,2023-09-07 06:53:25.764751,2023-09-07 07:21:17.170075+00,None,None,0
1,30,40,Jevon DuBuque,5.0,,Active,2023-09-08 11:33:42.626639,2025-05-01 12:22:48.803968+00,None,None,1
2,7,9,Colton O'Hara,5.0,,Active,2023-09-07 08:36:39.427031,2023-09-07 08:44:59.563982+00,None,None,0
3,9,13,Jamar Homenick Sr.,5.0,,Active,2023-09-07 09:16:03.645728,2023-09-07 09:38:39.91134+00,None,None,0
4,10,18,Hyman Hilll DDS,5.0,Oi,Active,2023-09-08 02:06:25.010408,2023-09-08 02:37:59.775269+00,None,None,0
...,...,...,...,...,...,...,...,...,...,...,...
40542,30555,45099,Ms. Kaitlin Bergstrom Jr.,5.0,"Hello my name is Jasmina Naomi, I’m a 22-year-...",Active,2025-06-25 16:31:04.808794,2026-02-13 13:30:17.457938+00,2003-07-18,Female,1
40543,6645,7108,Lori Jones,5.0,ik ben Gwen ik ben 19 jaar oud en ik vind het ...,Active,2024-02-08 18:10:33.697492,2026-02-13 13:30:18.052995+00,2005-12-21,Female,1
40544,19676,29413,Floy Schinner,4.0,,Active,2024-11-19 19:08:03.910463,2026-02-13 13:30:18.252477+00,1997-06-02,Female,1
40545,28193,40864,Lessie Schiller,5.0,Ik ben een enthousiast persoon die graag nieuw...,Active,2025-04-10 14:37:58.122307,2026-02-13 13:31:34.45252+00,2005-09-19,Female,3
40546,29196,42753,Ms. Bridie Schowalter IV,5.0,"Hey! I’m Chelsy, a 19-year-old from Antwerp wh...",Active,2025-05-24 19:56:07.258177,2026-02-13 13:29:26.552456+00,2006-01-26,Female,1

In [23]:
# df_creatorsmerged = pd.merge(df_creators, df_creatorsloc, left_on='id', right_on='influencer_id')


df_creatorsmerged = pd.merge(
    df_creators, 
    df_creatorsloc, 
    left_on='id', 
    right_on='influencer_id', 
    how='left'
)
df_creatorsmerged['country'] = df_creatorsmerged['country'].fillna('Unspecified')

df_creatorsmerged.loc[df_creatorsmerged.country == 'Nederland', 'country'] = "Netherlands"
df_creatorsmerged.loc[df_creatorsmerged.country == 'Belgique', 'country'] = "Belgium"
df_creatorsmerged.loc[df_creatorsmerged.country == 'België', 'country'] = "Belgium"
df_creatorsmerged.loc[df_creatorsmerged.country == 'UK', 'country'] = "United Kingdom"
df_creatorsmerged.loc[df_creatorsmerged.country == 'Deutschland', 'country'] = "Germany"


# 1. Get the list of countries that have more than 100 rows
counts = df_creatorsmerged['country'].value_counts()
top_countries = counts[counts > 100].index

# 2. Filter the original DataFrame to only include those countries
df_creatorsmerged = df_creatorsmerged[df_creatorsmerged['country'].isin(top_countries)]

In [26]:
df_creatorsmerged.country.value_counts()

country
Unspecified       21553
Netherlands       12689
Belgium            3209
United Kingdom     1510
Germany            1492
Spain               343
Name: count, dtype: int64

In [ ]:
# Set the 'race_date'
# We use August 2024 as the 't=0' point for the animation
start_date = min(df_creatorsmerged['created_at_x'])

df_creatorsmerged['race_date'] = df_creatorsmerged['created_at_x'].dt.to_period('W').dt.to_timestamp()

# 3. Create the pivot table
race_df = df_creatorsmerged.groupby(['race_date', 'country']).size().unstack(fill_value=0)

# 4. Cumulative sum
race_df = race_df.cumsum()

# Assuming race_df.index is already datetime
start_date = race_df.index.min()

# Create a custom label for the index
# This calculates the number of weeks/months since the start
def format_period(dt):
    # Example: "Jan 2025 | Week 18"
    weeks_since = ((dt - start_date).days // 7) + 1
    return f"{dt.strftime('%b %Y')} | Week {weeks_since}"

# Apply the new labels to the index
race_df.index = [format_period(dt) for dt in race_df.index]

In [ ]:
import bar_chart_race as bcr

# 1. Separate the "Unspecified" column from the rest
unspecified_counts = race_df['Unspecified']
visible_bars_df = race_df.drop(columns=['Unspecified'])

# 2. Filter for only Top 10 countries to keep the race focused
top_countries = visible_bars_df.iloc[-1].sort_values(ascending=False).head(15).index
visible_bars_df = visible_bars_df[top_countries]

# Calculate the TRUE total for each period (Visible + Unspecified)
# 'visible_bars_df' is your race dataframe
# 'unspecified_counts' is the series we separated earlier
total_per_period = visible_bars_df.sum(axis=1) + unspecified_counts

# Calculate the difference from the previous period (Growth)
weekly_new_users = total_per_period.diff().fillna(0)
growth_per_period = weekly_new_users.rolling(window=4, min_periods=1).sum().astype(int)


def summary(values, ranks):
    # 1. Get the Date & Total (same as before)
    current_date = values.name
    grand_total = int(total_per_period.loc[current_date])

    # 2. Get the Growth (New Apps/Creators this month)
    # We look up the pre-calculated value for this specific date
    new_last_30_days = growth_per_period.loc[current_date] 


    # 3. Dynamic Milestone Text
    milestone = ""
    if grand_total >= 40000: milestone = "40K!!!"
    elif grand_total >= 30000: milestone = "30K REACHED!"
    elif grand_total >= 20000: milestone = "20K REACHED!"
    elif grand_total >= 10000: milestone = "10K MILESTONE"
    
    # 4. Format the String
    # We add a new line for the growth speed
    # You can use standard arrows like '▲' or '↑' to indicate growth
    return {
        'x': .99, 'y': .20, 
        's': f'Total Creators: {grand_total:,}\n'
             f'(+{new_last_30_days:,} new past month)\n'
             f'{milestone}', 
        'ha': 'right', 'va': 'bottom', 'size': 11, 
        # 'family': 'Courier New' # Optional: Monospace fonts make numbers align better
    }




bcr.bar_chart_race(
    df=visible_bars_df, # "Unspecified" is not here!
    filename='creator_growth_race.mp4',
    title='Top Countries by Total Creators',
    # Adjusted label positions to avoid overlap
    period_label={'x': .99, 'y': .05, 'ha': 'right', 'va': 'bottom', 'size': 12},
    period_summary_func=summary,
    n_bars=10,
    steps_per_period=20,
    period_length=500,
    # Bar Chart Race styling
    filter_column_colors=True, # Colors stay with the country as they move
    # perpendicular_bar_func='mean', # Adds a vertical line showing the average
)



# bcr.bar_chart_race(
#     df=race_df,
#     filename='creator_growth_race.mp4',
#     title='Total Creators by Country',
#     period_label={'x': .99, 'y': .90, 'ha': 'right', 'va': 'top', 'size': 12},
#     n_bars=10,                # How many towns to show at once
#     steps_per_period=20,      # Smoothness of animation
#     period_length=500,        # Speed (ms)
#     period_summary_func=summary,
# )

/Users/wouterbarter/Documents/GitHub/AI_thesis-1/.venv312/lib/python3.12/site-packages/bar_chart_race/_make_chart.py:889: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_values.iloc[:, 0] = df_values.iloc[:, 0].fillna(method='ffill')
/Users/wouterbarter/Documents/GitHub/AI_thesis-1/.venv312/lib/python3.12/site-packages/bar_chart_race/_make_chart.py:286: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_yticklabels(self.df_values.columns)
/Users/wouterbarter/Documents/GitHub/AI_thesis-1/.venv312/lib/python3.12/site-packages/bar_chart_race/_make_chart.py:287: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))