In [1]:
from src.analysis.regression_models import create_regression_runner
from src.analysis.engine import AnalysisEnvironment
from src.utils import interactive_regression_results_selector

In [2]:
# Setup
env = AnalysisEnvironment(active_analysis='barter_deals')

# Load everything
final_df, og_df = env.load_data(raw_filename='BARTER_DEALS_CLEAN.parquet')
pm, prompt_map = env.load_prompts(prompt_subfolder='sandbox/BARTER_DEALS')

Loading files for analysis barter_deals
🐢 Running full processing pipeline...
Finished loading experiment data
Found 0 experimental trials contaminated by garbage output.
Found 2 different scale sizes: [np.int64(4), np.int64(5)]
  Processed 4000 rows with scale_size=4
  Processed 1000 rows with scale_size=5
Computing entropy for 2 different scale sizes: [np.int64(4), np.int64(5)]
  Processed 4000 rows with scale_size=4
  Processed 1000 rows with scale_size=5
PromptManager initialized with folder: ..\prompts\PromptSuites\sandbox\BARTER_DEALS
Scanning 3 suites from ..\prompts\PromptSuites\sandbox\BARTER_DEALS...
Loaded 3 PromptSuites

In [10]:
final_df

,applicants_applications_count,content_types,deal_id,main_image,min_social_media_followers,deal_tags,live_since,created_at,updated_at,deleted_at,...,top_k_tokens,constrained_tokens,sorted_tokens,sorted_logits,mean_rating,mode_rating,scale_size,entropy,normalized_entropy,first_content_type
0,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[4, 3, âģ, 5, ï¸ı, 2, âĳ, 1, 6, âĤ, 8, 7, **,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[22.272668838500977, 24.347896575927734, 32.4...",3.993179,4.0,4,0.040829,0.029452,Activities
1,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[3, 4, 2, ï¸ı, âģ, 5, **, 8, âĳ, 1, 7, Â³, 6,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[20.866113662719727, 25.588775634765625, 34.1...",3.147041,3.0,4,0.419342,0.302492,Activities
2,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[4, 3, ï¸ı, âģ, 5, 2, **, âŃĲ, 8, 7, âĳ, Ġ**,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[19.44389533996582, 22.37546157836914, 31.478...",3.866884,4.0,4,0.392396,0.283054,Activities
3,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[3, 4, 2, ï¸ı, 5, âģ, Â³, 1, **, 8, 6, 7, âĤ,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[21.82582664489746, 25.752683639526367, 36.06...",3.191083,3.0,4,0.488141,0.352119,Activities
4,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[5, 4, **, âģ, ï¸ı, 3, â, Ġ**, 6, âĳ, âĺħâĺħ,...","[1, 2, 3, 4, 5]","[1, 2, 3, 4, 5]","[[16.677732467651367, 15.764606475830078, 21.4...",4.975333,5.0,5,0.115684,0.071878,Activities
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[3, 2, 1, 4, 5, ï¸ı, 0, âĳ, Ġ**, Â², Â³, 6, Û...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[33.64588165283203, 35.53034591674805, 36.379...",2.627435,3.0,4,0.768372,0.554263,Food
4996,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[3, 2, 1, 4, ï¸ı, 5, Ġ**, 6, **, 0, Â², 7, âģ...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[30.365764617919922, 35.24386978149414, 36.29...",2.739364,3.0,4,0.593570,0.428170,Food
4997,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[1, 2, 3, 4, Ġ**, 0, ï¸ı, 5, Â¹, **, ðĿ, Â², ...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[36.18229675292969, 36.0102424621582, 33.6887...",1.523479,1.0,4,0.837614,0.604211,Food
4998,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[2, 3, 1, 4, 0, 5, ï¸ı, Â², Ġ**, âĤĤ, Û, 6, ð...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[36.65235137939453, 38.992000579833984, 37.26...",2.063434,2.0,4,0.659745,0.475905,Food
4999,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[4, 5, 3, **, 6, ï¸ı, âģ, 2, 1, Ġ**, 7, 8, 0,...","[1, 2, 3, 4, 5]","[1, 2, 3, 4, 5]","[[22.14377784729004, 23.017812728881836, 29.03...",4.004669,4.0,5,0.029720,0.018466,Food

# Data cleaning

We consider a number of filtering approaches. Content type is a strong predictor, but some have too few observations to obtain a stable parameter estimate. E.g., Finance and Photography have only 15 and 5 observations respectively, and with a coefficient of $\approx -23$, in a log model their coefficient is effectively zero. Since they have near-zero applications in the entire dataset, we waste degrees of freedom trying to fit tiny noisy groups. We suggest a to filter category size to only include ones that have "signal" in their observations.

In [15]:
valid_categories

Index(['Activities', 'Experiences', 'Food', 'UGC', 'Beauty', 'Fashion',
       'Luxury', 'Cooking', 'Lifestyle', 'Sport', 'Drinks', 'Travel',
       'Entertainment', 'Mom', 'Tech', 'Animals', 'Music', 'Cars', 'Gaming',
       'Finance', 'Nightlife', 'Vegan', 'Photography'],
      dtype='object', name='first_content_type')

In [16]:
final_df

,applicants_applications_count,content_types,deal_id,main_image,min_social_media_followers,deal_tags,live_since,created_at,updated_at,deleted_at,...,top_k_tokens,constrained_tokens,sorted_tokens,sorted_logits,mean_rating,mode_rating,scale_size,entropy,normalized_entropy,first_content_type
0,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[4, 3, âģ, 5, ï¸ı, 2, âĳ, 1, 6, âĤ, 8, 7, **,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[22.272668838500977, 24.347896575927734, 32.4...",3.993179,4.0,4,0.040829,0.029452,Activities
1,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[3, 4, 2, ï¸ı, âģ, 5, **, 8, âĳ, 1, 7, Â³, 6,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[20.866113662719727, 25.588775634765625, 34.1...",3.147041,3.0,4,0.419342,0.302492,Activities
2,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[4, 3, ï¸ı, âģ, 5, 2, **, âŃĲ, 8, 7, âĳ, Ġ**,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[19.44389533996582, 22.37546157836914, 31.478...",3.866884,4.0,4,0.392396,0.283054,Activities
3,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[3, 4, 2, ï¸ı, 5, âģ, Â³, 1, **, 8, 6, 7, âĤ,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[21.82582664489746, 25.752683639526367, 36.06...",3.191083,3.0,4,0.488141,0.352119,Activities
4,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[5, 4, **, âģ, ï¸ı, 3, â, Ġ**, 6, âĳ, âĺħâĺħ,...","[1, 2, 3, 4, 5]","[1, 2, 3, 4, 5]","[[16.677732467651367, 15.764606475830078, 21.4...",4.975333,5.0,5,0.115684,0.071878,Activities
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[3, 2, 1, 4, 5, ï¸ı, 0, âĳ, Ġ**, Â², Â³, 6, Û...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[33.64588165283203, 35.53034591674805, 36.379...",2.627435,3.0,4,0.768372,0.554263,Food
4996,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[3, 2, 1, 4, ï¸ı, 5, Ġ**, 6, **, 0, Â², 7, âģ...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[30.365764617919922, 35.24386978149414, 36.29...",2.739364,3.0,4,0.593570,0.428170,Food
4997,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[1, 2, 3, 4, Ġ**, 0, ï¸ı, 5, Â¹, **, ðĿ, Â², ...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[36.18229675292969, 36.0102424621582, 33.6887...",1.523479,1.0,4,0.837614,0.604211,Food
4998,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[2, 3, 1, 4, 0, 5, ï¸ı, Â², Ġ**, âĤĤ, Û, 6, ð...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[36.65235137939453, 38.992000579833984, 37.26...",2.063434,2.0,4,0.659745,0.475905,Food
4999,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[4, 5, 3, **, 6, ï¸ı, âģ, 2, 1, Ġ**, 7, 8, 0,...","[1, 2, 3, 4, 5]","[1, 2, 3, 4, 5]","[[22.14377784729004, 23.017812728881836, 29.03...",4.004669,4.0,5,0.029720,0.018466,Food

In [22]:
# 1. Define a minimum threshold (e.g., 50 observations)
MIN_OBSERVATIONS = 50

# 2. Count observations per category
counts = final_df['first_content_type'].value_counts()

# 3. Identify valid categories
valid_categories = counts[counts >= MIN_OBSERVATIONS].index.tolist()

print(f"Keeping {len(valid_categories)} categories: {valid_categories}")
print(f"Dropping: {counts[counts < MIN_OBSERVATIONS].index.tolist()}")

# 4. Filter the dataframe
# Only keep rows where the content type is in our valid list
filtered_df = final_df[final_df['first_content_type'].isin(valid_categories)].copy()

Keeping 16 categories: ['Activities', 'Experiences', 'Food', 'UGC', 'Beauty', 'Fashion', 'Luxury', 'Cooking', 'Lifestyle', 'Sport', 'Drinks', 'Travel', 'Entertainment', 'Mom', 'Tech', 'Animals']
Dropping: ['Music', 'Cars', 'Gaming', 'Finance', 'Nightlife', 'Vegan', 'Photography']

In [23]:
model_df = filtered_df

# Models

In [35]:
# 2. Define Variables (Move these to your config.yaml later!)
GROUPS = ['model_name', 'prompt_id']

###
TARGET = 'apps_after_7_days'
TARGET = 'apps_after_7_days_OLD'
# TARGET = 'applicants_applications_count'

###
# Categorical variables
CATS = []  # Empty as per your "LLM Eval only" test
# CATS = ['deal_type', 'first_content_type']

### 
# Binary variables
BINS = []
# BINS = ['accepts_international']  # Already 0/1 or T/F

###
# LLM evaluation variable
SCORE_VAR = 'mean_rating'

###
# Column for Clustered standard errors
CLUSTER_COL = 'partner_id'

## Regular errors

In [34]:
# Standard errors
runner = create_regression_runner(TARGET, GROUPS)
results = runner.run_negative_binomial(df=model_df,
                                       cat_vars=CATS,
                                       bin_vars=BINS,
                                       predictor_name=SCORE_VAR,
                                       dims_to_exclude=None)

interactive_regression_results_selector(results)

Dropdown(description='Select option:', layout=Layout(width='400px'), options=("('Qwen/Qwen3-4B-Instruct-2507',…

<class 'statsmodels.iolib.summary.Summary'>
"""
                   Generalized Linear Model Regression Results
=================================================================================
Dep. Variable:     apps_after_7_days_OLD   No. Observations:                  795
Model:                               GLM   Df Residuals:                      791
Model Family:           NegativeBinomial   Df Model:                            3
Link Function:                       Log   Scale:                          1.0000
Method:                             IRLS   Log-Likelihood:                -2826.8
Date:                   Tue, 03 Feb 2026   Deviance:                       1731.8
Time:                           10:14:16   Pearson chi2:                 1.94e+03
No. Iterations:                        8   Pseudo R-squ. (CS):           0.007603
Covariance Type:               nonrobust
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       2.4698      0.114     21.741      0.000       2.247       2.692
Clarity                     0.0747      0.076      0.982      0.326      -0.074       0.224
Persuasiveness             -0.2147      0.091     -2.354      0.019      -0.393      -0.036
Call-to-action strength     0.1731      0.072      2.406      0.016       0.032       0.314
===========================================================================================
"""

## Clustered errors

In [ ]:
# Clustered errors
runner = create_regression_runner(TARGET, GROUPS, cluster_col='partner_id')
results = runner.run_negative_binomial(model_df, CATS, BINS, SCORE_VAR)
# results = runner.run_negative_binomial(final_df, CATS, BINS, SCORE_VAR, dims_to_exclude=['Clarity', 'Persuasiveness'])

interactive_regression_results_selector(results)

Dropdown(description='Select option:', index=2, layout=Layout(width='400px'), options=("('Qwen/Qwen3-4B-Instru…

<class 'statsmodels.iolib.summary.Summary'>
"""
                   Generalized Linear Model Regression Results
=================================================================================
Dep. Variable:     apps_after_7_days_OLD   No. Observations:                  795
Model:                               GLM   Df Residuals:                      776
Model Family:           NegativeBinomial   Df Model:                           18
Link Function:                       Log   Scale:                          1.0000
Method:                             IRLS   Log-Likelihood:                -2776.7
Date:                   Tue, 03 Feb 2026   Deviance:                       1631.7
Time:                           10:12:51   Pearson chi2:                 1.56e+03
No. Iterations:                       10   Pseudo R-squ. (CS):             0.1250
Covariance Type:                 cluster
====================================================================================================
                                       coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
const                                2.3492      0.296      7.931      0.000       1.769       2.930
mean_rating                         -0.0300      0.065     -0.459      0.646      -0.158       0.098
accepts_international               -0.2295      0.148     -1.555      0.120      -0.519       0.060
deal_type_physical                  -0.2215      0.129     -1.715      0.086      -0.475       0.032
first_content_type_Animals           0.0405      0.546      0.074      0.941      -1.030       1.111
first_content_type_Beauty            0.4332      0.268      1.619      0.105      -0.091       0.958
first_content_type_Cooking          -0.0345      0.265     -0.130      0.896      -0.554       0.485
first_content_type_Drinks            0.6388      0.387      1.651      0.099      -0.120       1.397
first_content_type_Entertainment    -0.4380      0.325     -1.346      0.178      -1.076       0.200
first_content_type_Experiences       0.4694      0.233      2.016      0.044       0.013       0.926
first_content_type_Fashion           0.9703      0.253      3.841      0.000       0.475       1.465
first_content_type_Food              0.3748      0.208      1.804      0.071      -0.032       0.782
first_content_type_Lifestyle         0.1910      0.333      0.573      0.567      -0.463       0.845
first_content_type_Luxury            0.6275      0.272      2.307      0.021       0.094       1.161
first_content_type_Mom              -0.0035      0.340     -0.010      0.992      -0.670       0.663
first_content_type_Sport            -0.5441      0.378     -1.441      0.150      -1.284       0.196
first_content_type_Tech             -0.0584      0.302     -0.193      0.847      -0.651       0.534
first_content_type_Travel            0.3024      0.340      0.890      0.373      -0.363       0.968
first_content_type_UGC               0.6497      0.218      2.985      0.003       0.223       1.076
====================================================================================================
"""

-------------

# EDA

## DF with LLM ratings

In [7]:
final_df

,applicants_applications_count,content_types,deal_id,main_image,min_social_media_followers,deal_tags,live_since,created_at,updated_at,deleted_at,...,top_k_tokens,constrained_tokens,sorted_tokens,sorted_logits,mean_rating,mode_rating,scale_size,entropy,normalized_entropy,first_content_type
0,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[4, 3, âģ, 5, ï¸ı, 2, âĳ, 1, 6, âĤ, 8, 7, **,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[22.272668838500977, 24.347896575927734, 32.4...",3.993179,4.0,4,0.040829,0.029452,Activities
1,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[3, 4, 2, ï¸ı, âģ, 5, **, 8, âĳ, 1, 7, Â³, 6,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[20.866113662719727, 25.588775634765625, 34.1...",3.147041,3.0,4,0.419342,0.302492,Activities
2,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[4, 3, ï¸ı, âģ, 5, 2, **, âŃĲ, 8, 7, âĳ, Ġ**,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[19.44389533996582, 22.37546157836914, 31.478...",3.866884,4.0,4,0.392396,0.283054,Activities
3,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[3, 4, 2, ï¸ı, 5, âģ, Â³, 1, **, 8, 6, 7, âĤ,...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[21.82582664489746, 25.752683639526367, 36.06...",3.191083,3.0,4,0.488141,0.352119,Activities
4,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,"[[5, 4, **, âģ, ï¸ı, 3, â, Ġ**, 6, âĳ, âĺħâĺħ,...","[1, 2, 3, 4, 5]","[1, 2, 3, 4, 5]","[[16.677732467651367, 15.764606475830078, 21.4...",4.975333,5.0,5,0.115684,0.071878,Activities
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[3, 2, 1, 4, 5, ï¸ı, 0, âĳ, Ġ**, Â², Â³, 6, Û...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[33.64588165283203, 35.53034591674805, 36.379...",2.627435,3.0,4,0.768372,0.554263,Food
4996,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[3, 2, 1, 4, ï¸ı, 5, Ġ**, 6, **, 0, Â², 7, âģ...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[30.365764617919922, 35.24386978149414, 36.29...",2.739364,3.0,4,0.593570,0.428170,Food
4997,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[1, 2, 3, 4, Ġ**, 0, ï¸ı, 5, Â¹, **, ðĿ, Â², ...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[36.18229675292969, 36.0102424621582, 33.6887...",1.523479,1.0,4,0.837614,0.604211,Food
4998,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[2, 3, 1, 4, 0, 5, ï¸ı, Â², Ġ**, âĤĤ, Û, 6, ð...","[1, 2, 3, 4]","[1, 2, 3, 4]","[[36.65235137939453, 38.992000579833984, 37.26...",2.063434,2.0,4,0.659745,0.475905,Food
4999,27,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",019689e2-66eb-00c8-ddf3-ca9a3d063b80,uploads/deals/019689e2-67b0-ffff-c05b-fbc204bf...,2500,None,2025-02-26 21:55:50.754848,2025-02-26 21:55:50.754848,2025-10-28 10:50:43.934652,NaT,...,"[[4, 5, 3, **, 6, ï¸ı, âģ, 2, 1, Ġ**, 7, 8, 0,...","[1, 2, 3, 4, 5]","[1, 2, 3, 4, 5]","[[22.14377784729004, 23.017812728881836, 29.03...",4.004669,4.0,5,0.029720,0.018466,Food

In [8]:
final_df.first_content_type.value_counts()

first_content_type
Activities       935
Experiences      660
Food             645
UGC              525
Beauty           370
Fashion          360
Luxury           330
Cooking          170
Lifestyle        165
Sport            150
Drinks           125
Travel           110
Entertainment    105
Mom               70
Tech              65
Animals           50
Music             45
Cars              45
Gaming            25
Finance           15
Nightlife         10
Vegan             10
Photography        5
Name: count, dtype: int64

## Raw data

In [36]:
og_df

,applicants_applications_count,content_types,deal_id,main_image,min_social_media_followers,deal_tags,live_since,created_at,updated_at,deleted_at,...,legacy_id,tags,gender,featured_image,company_id,test_nr_of_apps,update_at_date,diff,apps_after_7_days,apps_after_7_days_OLD
0,39,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",0196edc7-e6a8-00c8-6ff5-ea60fa3f2895,uploads/deals/0196edc7-5969-ffff-6700-7ae699b8...,2500,None,2025-05-20 15:21:28.249567,2025-05-20 13:00:23.080212,2025-10-28 10:55:34.719187,NaT,...,NaN,None,None,None,0199f1d4-b501-015e-5c45-1bc8300b3949,39,2025-10-28,0,39,39.0
1,0,"[{'id': 21, 'name': 'Fashion', 'slug': 'Dress'}]",019689e5-f489-00c8-8c26-06b3ea0961a5,uploads/deals/019689e5-f54b-ffff-dbed-637e9d2a...,5000,None,2023-11-28 14:59:51.626780,2023-11-28 14:59:51.626780,2025-05-01 03:31:11.600095,NaT,...,487.0,None,None,None,None,0,2025-05-01,0,0,0.0
2,23,"[{'id': 29, 'name': 'UGC', 'slug': 'Film-Strip'}]",019689e2-bfb5-00c8-6485-23352d64b0e5,uploads/deals/019689e2-c06c-ffff-baf0-c7e9decd...,5000,None,2025-03-04 11:46:18.176627,2025-03-04 11:46:18.176627,2025-05-01 03:27:41.316646,NaT,...,3593.0,None,None,None,None,23,2025-05-01,0,13,13.0
3,43,"[{'id': 21, 'name': 'Fashion', 'slug': 'Dress'}]",019689e3-d7a5-00c8-f5a8-6bfe51a21cd6,uploads/deals/019689e3-d86f-ffff-a03e-d38765a0...,2500,None,2025-04-17 09:50:45.518632,2025-04-17 09:50:45.518632,2025-06-08 09:05:21.413273,NaT,...,4228.0,None,None,None,None,43,2025-06-08,0,19,19.0
4,13,"[{'id': 19, 'name': 'Sport', 'slug': 'Soccer-B...",019689e5-7dd0-00c8-615b-7750a8fec2f3,uploads/deals/019689e5-7f9d-ffff-5b6d-a335c1ce...,2500,None,2025-02-10 18:19:51.240203,2025-02-10 18:19:51.240203,2025-10-28 10:51:05.147656,NaT,...,3242.0,None,None,None,0199f1b0-2b6c-015e-e5b3-6b1dd7564d3a,13,2025-10-28,0,13,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5106,9,"[{'id': 39, 'name': 'Experiences', 'slug': 'Te...",019689e5-4642-00c8-08dd-41d776586f1c,uploads/deals/019689e5-46b6-ffff-2159-fb70a484...,50000,None,2024-03-26 14:09:02.539962,2024-03-26 14:09:02.539962,2025-10-28 10:54:41.617599,NaT,...,865.0,None,None,None,0199f1cc-e3f7-015e-432a-d2035c7ba015,9,2025-10-28,0,5,5.0
5107,11,"[{'id': 39, 'name': 'Experiences', 'slug': 'Te...",019689e5-6ce0-00c8-5fdd-a058811d2946,uploads/deals/019689e5-6e0d-ffff-4a2f-362bb635...,10000,None,2024-10-17 14:59:27.484092,2024-10-17 14:59:27.484092,2025-10-28 10:52:42.692581,NaT,...,1889.0,None,None,None,0199f1c3-fcaf-015e-eeb9-cc244704412b,11,2025-10-28,0,7,7.0
5108,0,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}]",0198324e-635d-00c8-7d1d-bbb0b902b0d9,,10000,None,NaT,2025-07-22 13:24:14.813323,2025-10-28 11:04:12.121141,NaT,...,NaN,None,None,None,0199f18e-af17-015e-23aa-c780e5c4a2b8,0,2025-10-28,0,0,NaN
5109,0,"[{'id': 41, 'name': 'Activities', 'slug': 'per...",01983c98-87ee-00c8-e551-8fd9afde13aa,,5000,None,NaT,2025-07-24 13:21:25.998303,2025-10-28 10:51:32.951354,NaT,...,NaN,None,None,None,0199f1b6-5645-015e-ffbf-5e1786a1e5c3,0,2025-10-28,0,0,NaN
5110,11,"[{'id': 23, 'name': 'Food', 'slug': 'Pizza'}, ...",01985b50-e6ec-00c8-6e60-feda42ee959b,uploads/deals/01985b50-e749-ffff-7870-e6157feb...,10000,None,2025-07-30 12:32:26.149352,2025-07-30 12:31:25.420062,2025-10-28 10:50:04.770145,NaT,...,NaN,None,None,None,0199f1a3-3d16-015e-52ca-006b924bdcfc,11,2025-10-28,0,10,10.0